.Dd 9/8/13               \" DATE 
.Dt UCVM 1      \" Program name and manual section number 
.Os Linux
.Sh NAME                 \" Section Header - required - don't modify 
.Nm ecompact
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl h
input 
output
.Sh DESCRIPTION          \" Section Header - required - don't modify
The command
.Nm
helps compact an e-tree file that conforms either to CMU or SCEC standards. 
It does this by removing empty space in the Etree data structure. Usually, this command
is run with 
.Nm ecoalesce 
as well.
.Pp
.Bl -tag -width -indent 
Common Paramters
.It Fl h
Shows the help message.
.It input
E-tree input file. Typically, this was just extracted with the ucvm2etree utilities.
.It output
Compacted e-tree output.
.El
.Sh EXAMPLE
.Pp                      \" Inserts a space
.Nm
chino_hills.etree compacted_chino_hills.etree
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr ecoalesce 1 ,
.Xr ucvm2etree 1 ,
.Xr ucvm2etree-extract-MPI 1 ,
.Xr ucvm2etree-merge-MPI 1 ,
.Xr ucvm2etree-sort-MPI 1