#!/bin/bash

#PBS -q default
#PBS -l arch=x86_64,pmem=2000mb,pvmem=3000mb,walltime=1:00:00,nodes=4:ppn=4
#PBS -V
#PBS -e /home/rcf-104/patrices/cvm2mesh/trunk/pbs/hpc/test_cvmh_core16.err
#PBS -o /home/rcf-104/patrices/cvm2mesh/trunk/pbs/hpc/test_cvmh_core16.out

SRC_DIR=/home/rcf-104/patrices/cvm2mesh/trunk/src

cd /scratch
cp ${SRC_DIR}/mesh-create-MPI .
cp ${SRC_DIR}/../conf/hpc/*.conf .

#mkdir cvmh
#cd cvmh
#cp /home/rcf-104/patrices/utils/cvmh/bin/* .
#cd ..

mpirun -np 16 ./mesh-create-MPI -o ${SRC_DIR} -f test_cvmh_core16.conf


echo "Jobs done"
date
exit 0
